### ISSUE TITLE
Design layout for tablet devices

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#306]

**Comment by jjoseba** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;FDVcwLMF&#x2F;4-and-crear-layout-para-tablet-y-ver-las-adaptaciones-necesarias"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [AND] Crear layout para tablet (y ver las adaptaciones necesarias</a>

**Comment by alexlittle** [comment]
Needs to be designed and planned first

**Comment by alexlittle** [comment]
Moved to discourse: https://community.oppia-mobile.org/t/tablet-focused-design-ideas/34
