### ISSUE TITLE
context menu of the main activity into a drawer

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#421]

**Comment by jjoseba** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;NGssT1Qj&#x2F;5-and-convertir-menu-principal-en-navigation-drawer"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [AND] Convertir menú principal en Navigation Drawer</a>

**Comment by alexlittle** [comment]
Tabs are now a lot smaller, so the text doesn't appear well (lots cut off):

![screenshot_2016-03-07-11-43-19](https://cloud.githubusercontent.com/assets/344917/13565732/a008ab58-e45a-11e5-9bbe-fc958cebed26.png)

**Comment by alexlittle** [comment]
Also please can we keep the standard "rounded square" version of the Digital Campus logo in the navigation drawer header - without the shading.

![screenshot_2016-03-07-11-55-49](https://cloud.githubusercontent.com/assets/344917/13565972/ebd8aeba-e45b-11e5-9b5e-3d47eba6596e.png)

**Comment by alexlittle** [comment]
Sorry - please can we remove the diagonal shadow behind the icon as well ?
