### ISSUE TITLE
nicer onboarding

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#422]

**Comment by jjoseba** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8cOMRQnC&#x2F;10-and-mejorar-el-onboarding-registro-y-login"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [AND] Mejorar el onboarding (registro y login)</a>
