### ISSUE TITLE
Can't start app with storage location set to external

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#464]
and also can;t change to external storage option - seems to be an error when creating the dirs (in the sdcard1/Android/data/ dir there is no dir for org.digitalcampus...)

**Comment by jjoseba** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;VvoTTPPw&#x2F;3-and-ver-problema-con-el-almacenamiento-en-sd-en-el-motorola-g"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [AND] Ver problema con el almacenamiento en SD en el motorola G</a>

**Comment by alexlittle** [comment]
Working now, just minor change to use either the right Oppia logo (or no logo) in the information screen
