### ISSUE TITLE
Update activity task - give feedback if successful or not

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#471]

**Comment by jjoseba** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HkFLN1sE&#x2F;2-and-informar-del-progreso-de-la-tarea-de-actualizar-una-actividad"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [AND] Informar del progreso de la tarea de actualizar una actividad</a>
