### ISSUE TITLE
Allow setting up of admin password for accessing settings and course management

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#474]

**Comment by alexlittle** [comment]
The preferences, should be an option to add a device admin password - if this is empty then user can access all functions, if not then access to functions specified (below) will be restricted.

In the MobileLearning class we should be able to define which options are protected by the password, currently these should be:
default_admin_password = ""/null
admin_protect_settings - to prevent access to the settings pages
admin_protect_course_delete - to prevent removal of course form the device
admin_protect_course_reset - to prevent course activity being reset
admin_protect_course_install - to prevent installation of new courses
admin_protect_course_update - to prevent courses being updated

The reason for defining what gets protected by the password is to allow other implementations to set their own policies for what gets protected by this password.

**Comment by jjoseba** [comment]
And could be managed via preferences which of this options are protected or not by password? Or are they defined as a constant value in MobileLearning class?

**Comment by alexlittle** [comment]
At this stage I don;t think we need to have the options managed in the preferences - just as constants in the MobileLearning class. The reason being that this is likely to be a policy for a particular implementation (forked version of Oppia app), so they won't necessarily want to have to configure every device? (although of course they'll still have to set the password).
