### ISSUE TITLE
How to pre-load accounts onto the device

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#480]
Suggest reading from a text (CVS) file - and then will allow users to login initially even if no connection is available. Need to think how the data could be stored safely - only a hash of the password is needed, not the actual password

**Comment by jjoseba** [comment]
To go further in the security aspect, to store the data more safely than in a plain text file we can think of using some easy encryption algorithm. Problem: the encryption key must be available in both the server and the app, and could led to compatibility issues. But for the purpose the functionality is conceived - preloading accounts related to a concrete well-known Oppia server - I guess it will make it.

**Comment by alexlittle** [comment]
Perhaps an easier way to deal with this is to ignore the part about the server exporting the file. So instead just a function within the app to read in a CVS file with the account details (likely use the same format as is uploaded to the server). The projects who are likely to want/need this will have set up the accounts on the server anyway and will know the passwords.
