### ISSUE TITLE
Invalidate user apiKey?

### ISSUE THREAD

**Issue by jjoseba** [DigitalCampus/oppia-mobile-android#510]
With the current approach of login users locally, there can be an scenario as following:

1. User logs in the app, and her username/apiKey gets stored in the device
2. The apiKey gets invalidated by some reason
3. The user cannot longer communicate with the API, as it will return always 401 responses

To solve this, the app could invalidate an apiKey once it gets an Auth error from the server, so the user has to login again and get a new apiKey.

**Comment by alexlittle** [comment]
Thanks - yes that seems to be a good approach.
