### ISSUE TITLE
In quiz activity - if user has passed then show option to continue rather than retake

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#526]
Feedback from user: 

In the quiz, after selecting a response, the user is given the option to retake the quiz whether their response was correct or incorrect. If the user was correct is there anyway we can just continue on to the next screen? Is there a continue option? I’m trying to avoid the potential confusing this retake option might bring to our teams and end users

**Comment by jjoseba** [comment]
It was solved in https://github.com/DigitalCampus/oppia-mobile-android/pull/548

**Comment by alexlittle** [comment]
Thanks - I saw it had been implemented with the continue option. Just one minor item to change/update here.... At the end of a pre-test/baseline quiz the text should be "Continue to course", but at the end of a quiz in the normal part of a course, it should just be "Continue" - currently it seems to be showing "Continue to course" for all the quizzes?
