### ISSUE TITLE
 java.lang.ClassCastException: org.digitalcampus.oppia.task.CourseSizeTask cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#535]
With app version 5.3 - not sure if applies to later versions too?

Error Message

java.lang.ClassCastException: org.digitalcampus.oppia.task.CourseSizeTask cannot be cast to java.lang.String

Where

DownloadCourseListAdapter.java:120

Short Stacktrace
0 	java.lang.ClassCastException: org.digitalcampus.oppia.task.CourseSizeTask cannot be cast to java.lang.String
1 	at org.digitalcampus.oppia.adapter.DownloadCourseListAdapter.getView(DownloadCourseListAdapter.java:120)
2 	at android.widget.AbsListView.obtainView(AbsListView.java:2743)
3 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1274)
4 	at android.widget.ListView.onMeasure(ListView.java:1186)
5 	at android.view.View.measure(View.java:17460)
6 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
7 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
8 	at android.view.View.measure(View.java:17460)
9 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
10 	at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:409)
11 	at android.view.View.measure(View.java:17460)
12 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
13 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
14 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2545)
15 	at android.view.View.measure(View.java:17460)
16 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2193)
17 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1381)
18 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1563)
19 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1239)
20 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6396)
21 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
22 	at android.view.Choreographer.doCallbacks(Choreographer.java:613)
23 	at android.view.Choreographer.doFrame(Choreographer.java:583)
24 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
25 	at android.os.Handler.handleCallback(Handler.java:733)
26 	at android.os.Handler.dispatchMessage(Handler.java:95)
27 	at android.os.Looper.loop(Looper.java:146)
28 	at android.app.ActivityThread.main(ActivityThread.java:5511)
29 	at java.lang.reflect.Method.invokeNative(Native Method)
30 	at java.lang.reflect.Method.invoke(Method.java:515)
31 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
32 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
33 	at dalvik.system.NativeStart.main(Native Method)

**Comment by jjoseba** [comment]
Where does this come from? There is no org.digitalcampus.oppia.task.CourseSizeTask class in the project, neither any cast to String in the adapter method. I guess this does not apply to the current version.

**Comment by alexlittle** [comment]
It's from v5.3 - so probably we can ignore for now - unless we start to 
see with more recent versions.

A

On 28/04/16 13:45, Joseba S. wrote:
>
> Where does this come from? There is no 
> org.digitalcampus.oppia.task.CourseSizeTask class in the project, 
> neither any cast to String in the adapter method. I guess this does 
> not apply to the current version.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/DigitalCampus/oppia-mobile-android/issues/535#issuecomment-215384861>
>


-- 
Alex Little
Director, Digital Campus
alex@digital-campus.org
http://digital-campus.org
mobile (UK): +44 7548 236 650
mobile (Finland): +358 45 640 2013
skype: alexlittleou
twitter: @digicampusteam <https://twitter.com/digicampusteam> & 
@alexlittle <https://twitter.com/alexlittle>

**Comment by alexlittle** [comment]
Closing as only appears in older versions
