### ISSUE TITLE
ListPreference requires an entries array and an entryValues array.

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#555]
Where

Native Method

Short Stacktrace
0 	java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
1 	at android.preference.ListPreference.onPrepareDialogBuilder(ListPreference.java:240)
2 	at android.preference.DialogPreference.showDialog(DialogPreference.java:307)
3 	at android.preference.DialogPreference.onClick(DialogPreference.java:278)
4 	at android.preference.Preference.performClick(Preference.java:1052)
5 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:229)
6 	at android.widget.AdapterView.performItemClick(AdapterView.java:308)
7 	at android.widget.AbsListView.performItemClick(AbsListView.java:1513)
8 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3471)
9 	at android.widget.AbsListView$3.run(AbsListView.java:4838)
10 	at android.os.Handler.handleCallback(Handler.java:733)
11 	at android.os.Handler.dispatchMessage(Handler.java:95)
12 	at android.os.Looper.loop(Looper.java:146)
13 	at android.app.ActivityThread.main(ActivityThread.java:5641)
14 	at java.lang.reflect.Method.invokeNative(Native Method)
15 	at java.lang.reflect.Method.invoke(Method.java:515)
16 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288)
17 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104)
18 	at dalvik.system.NativeStart.main(Native Method)
Tag
log
Affected App Versions

5.5
Affected OS Versions

4.4.2

**Comment by jjoseba** [comment]
To reproduce:
 1. login to the main screen
 2. remove any installed course so we don't have any
 3. go to the settings screen and try to change the preferred language option
