### ISSUE TITLE
Phone no - will only accept up to 10 digits - should be longer

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#561]
As doesn't allow for adding any country code

**Comment by jjoseba** [comment]
Could this be related with the `inputType="phone"` and the country you are in? I've tested it in different phones with APIs 19, 21 and 23 and I can introduce more than 10 digits, and the plus sign too.

**Comment by alexlittle** [comment]
can't recreate - so closing for now
