### ISSUE TITLE
Logging when cron was last run

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#563]
Could be quite easy for people to set up the server but without setting up the cron task, should flag up to admins if it's not been run recently - possibly also storing in the oppia server settings table.

**Comment by jjoseba** [comment]
I guess this one should go in the django project?

**Comment by alexlittle** [comment]
Oops, yes, should be under the server task list - have added now: https://github.com/DigitalCampus/django-oppia/issues/364
