### ISSUE TITLE
Update CSS file for list indentation

### ISSUE THREAD

**Issue by AlbertoMoreta** [DigitalCampus/oppia-mobile-android#598]
![image](https://cloud.githubusercontent.com/assets/17184628/20300653/692a1706-ab20-11e6-9867-f882e172ebe1.png)

For example, the lines with dots should be one step to the right respect to the lines with numbers

**Comment by alexlittle** [comment]
Thanks Alberto - have moved this over to the Moodle block issue list - as the CSS file is actually held there then copied out when the block is exported (so each course could use a different stylesheet) - see: https://github.com/DigitalCampus/moodle-block_oppia_mobile_export/issues/167
