### ISSUE TITLE
Activity completion sequencing not working correctly

### ISSUE THREAD

**Issue by jamesbt** [DigitalCampus/oppia-mobile-android#604]
We've configure the export of a course from Moodle to require completion of each activity (e.g., watching an entire video or getting a 100% on a quiz) before a user can progress. When accessing the course in the app, it doesn't appear as though the completion of activities is being logged properly. For example, even after watching an entire video the app throws a message saying the activity has to be completed before continuing. The same with the quizzes: even after getting 100%, users cannot progress to the next activity. If they exit out of the module and then go back in, then they can progress. Similarly, if they take the quiz 3 times in a row, each time scoring a 100%, they can then continue.

**Comment by alexlittle** [comment]
transferred to OPPIA-126
