### ISSUE TITLE
OppiaMobile server setting

### ISSUE THREAD

**Issue by jamesbt** [DigitalCampus/oppia-mobile-android#605]
I've noticed that if I forget to add a trailing slash ("/") to the URL for the OppiaMobile server in the app settings then I get a connection error. Maybe a regex could be added to the code to make sure that: 1) people enter a well-formed URL, and 2) they include a trailing slash. And perhaps that slash could be appended automatically if people forget to enter it.

**Comment by alexlittle** [comment]
The app should have been checking for the trailing slash, but seems for some reason it's not working anymore
