### ISSUE TITLE
Prevent install of app on Android versions higher than we've tested on

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#612]
Eg. there are issues with v7, but of course we've never tried on this - so should prevent install in the first place until we've tested to ensure it's compatible

**Comment by jjoseba** [comment]
In theory, from the Android documentation (https://developer.android.com/guide/topics/manifest/uses-sdk-element.html):
- `android:targetSdkVersion`: However, if the API level of the platform is higher than the version declared by your app's targetSdkVersion, the system may enable compatibility behaviors to ensure that your app continues to work the way you expect.
- `android:maxSdkVersion`: **declaring it is not recommended**. Future versions of Android (beyond Android 2.0.1) will no longer check or enforce the `maxSdkVersion` attribute during installation or re-validation. Google Play will continue to use the attribute as a filter, however, when presenting users with applications available for download.

So according to this, we are doing everything we are capable of... another option would be to check the Android version at startup and exit the application if it is above our target version, but maybe is too radical?

**Comment by alexlittle** [comment]
Thanks - as you say forcing the app to close I think will be too radical! I'll close this now since it seems there's not much we can really do here. I was a little surprised that someone in Zambia had an Android running v7 though - so perhaps they've just made a mistake?
