### ISSUE TITLE
OPPIA_SERVER_DEFAULT in Nepal

### ISSUE THREAD

**Issue by jonathanclarke** [DigitalCampus/oppia-mobile-android#623]
Hi Alex,

Helping out  (Moon Pradhan) who is using Oppia Mobile in Johns Hopkins Nepal for one of their programs to create this issue.  

Is it possible to upload the APK for the play store in Nepal with a default OPPIA_SERVER_DEFAULT set to http://nepal.ccp-ict.org

There is a huge barrier for their users in Nepal to input the new server settings.  Is this anything that you can help out with?

**Comment by alexlittle** [comment]
Hi Jonathan - I'll send a direct message about this, but essentially to change the default server setting you'll need to have a clone of the app code, update the default server, then recompile and ask the users to install this new version.

**Comment by jonathanclarke** [comment]
Yep, thought so.   I forwarded on that recommendation yesterday to her.   Thanks so much for the quick reply.  Will follow up by email. Closing this one.
