### ISSUE TITLE
After install save the original course zip file

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#658]
Add a new dir on the app file system for this and save the file name/reference in the course table in the app database.
Currently the zip files are just deleted after being unzipped - but for transferring courses to other devices, it'll be better to keep the original zip

**Tests needed:**
Check the new directory is created and the installed courses all have corresponding files in this dir

**Documentation needed:**
none

**Comment by jjoseba** [comment]
Will have to take into account some scenarios:
* if there is already a version of the course in the courses backup folder, check that this version is newer and remove the older one. Would be interesting to save somewhere the course version of the currently saved backup?
* if a course is uninstalled from the device, also delete the backup zip file
* if a course zip comes with tracker data (of the user that downloaded it), delete this personal info of the zip file
