### ISSUE TITLE
Develop designs for how the leaderboard may be displayed in the app

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#672]
There are a lot of options and possibilities here, so all that needs to be done int he first instance is come up with domes drawings/sketches and overview info about how it will work - no specific tech dev for this - once the approach is decide on, then we can start to implement it.

**Automatic Tests:**
none - as a design/interface decision only at this point

**Documentation:**
none

**Comment by jjoseba** [comment]
I've thought about something along these lines... (it is done directly in the Android designer, so the implementation would be very straight-forward):
![leaderboard_design](https://user-images.githubusercontent.com/6810415/41972236-82e7322a-7a11-11e8-9fe1-c3e1a5bffef6.jpg)
