### ISSUE TITLE
Remove this "return" statement or make it conditional.

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#710]
in /mobile/
quiz/Quiz.java - L317
quiz/model/Response.java - L41 
quiz/model/Response.java - L90
quiz/model/questiontypes/DragAndDrop.java - L120
quiz/model/questiontypes/Matching.java - L96
quiz/model/questiontypes/MultiChoice.java - L98
quiz/model/questiontypes/ShortAnswer.java - L100

**Comment by hemantsonu20** [comment]
I would like to take this issue. But need some more information.
Eg. Response.java L41:
```
else if (!title.entrySet().isEmpty()) {
            return title.entrySet().iterator().next().getValue();
        }
````
We can refactor its as
```
else if (!title.isEmpty()) {
            return title.entrySet().iterator().next().getValue();
        }
```
Is it fine? I didn't get the issue titlee "remove this return or make it conditional".

**Comment by alexlittle** [comment]
Hi @hemantsonu20  - thanks for your interest in contributing and apologies for delay getting back to you - I was at workshop last week, so just catching up with messages now...

I think this issue might already have been resolved. For info, these issues were created from the advice given on the SonarQube analysis - so you can see more here: https://sonarcloud.io/dashboard?id=oppia-mobile-android%3Aapp, if you are looking for some (easy-ish) fixes to contribute to the code, then there are quite a lot! especially the issues marked as 'minor' should be be quick/straightforward fixes,
thanks again,
Alex
