### ISSUE TITLE
App awards points for course download when the download fails

### ISSUE THREAD

**Issue by studiosi** [DigitalCampus/oppia-mobile-android#731]
The app awards 50 points per course download, even when the download fails for whatever reason (error message appears properly and otherwise the app seems to behave correctly).

Disregard and close this issue if this gamification aspect is going to be removed.

**Comment by jjoseba** [comment]
It was solved in https://github.com/DigitalCampus/oppia-mobile-android/commit/40c0e9854625c2e6b9f670901227dab0dcd4a0bc (pending to be merged in the main branch)
