### ISSUE TITLE
SonarQube & Testing: Disable XML external entity (XXE) processing

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#784]
see: https://sonarcloud.io/project/issues?id=org.digitalcampus.mobile.learning&resolved=false&sonarsourceSecurity=xxe&types=VULNERABILITY for specific instances in the code

Plus add tests to make sure the refactoring hasn't broken anything

**Comment by Niotree** [comment]
Hello, I have the same mistake and I corrected it but sonar found it again. Have you been able to correct it?
Thank you

**Comment by alexlittle** [comment]
Hi @Niotree  - we've not got it fixed up yet, but it's an issue to cover in our next code sprint (in Nov), so hopefully in a few weeks we'll have it fixed up!
Cheers,
Alex

**Comment by Niotree** [comment]
Okay, thank you. And do you know if we can tell sonar to forget a vulnerability it found but we know it's fixed but it still finds?

**Comment by alexlittle** [comment]
No not yet - it's something we looked at too, esp for highlighting that potential security vulnerabilities have been checked over, so no longer needs to be highlighted in sonarcloud.
My guess though would be that they don;t provide an option to do this, since otherwise it'd be too easy for people to make it look like the code is passing all the tests (just my cynical side coming out!)

**Comment by alexlittle** [comment]
transferred to OPPIA-109
