### ISSUE TITLE
Saved courses appear across different accounts

### ISSUE THREAD

**Issue by jbc25** [DigitalCampus/oppia-mobile-android#786]
When registering new account, list of courses have the same items than the previous account

**Comment by alexlittle** [comment]
Actually this is a feature rather than a bug!
The course list should be the same for all users on a device, so each user doesn't need to download the course/media etc.
I presume though that it doesn't show the activity/progress of the previous logged in user?

**Comment by alexlittle** [comment]
Closing this now as nothing needed to do
