### ISSUE TITLE
Activity data not available for export

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#815]
From email:
"In one instance, a device showed data available to submit, but wouldn't allow me to export. This may be because I had already transferred data off of the device, but from what I can tell, there is no way to return # of files to submit back to 0 without connecting to the internet."

**Comment by jjoseba** [comment]
This is not a bug but just how it is working right now. The way it is currently implemented, the "to submit" figure shows the number of trackers registered in the device that have no confirmation to be registered in the server. Until we come up with a mechanism to notify this offline device that those trackers are successfully submitted, that number cannot go back to zero...

**Important**: In the last part Nick talks about "# of files" - these are not files, but individual activity trackers.
