### ISSUE TITLE
Transferred activity data not available for submission to server

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#816]
From email:
" I transferred activity and registration data from Device A to Device B. Device B reported "0 to submit" even though I could see two different .JSON files ready for sending (see screenshot). Ultimately, I was not able to get this information to send to the server. Like above, I received an error connecting to server message despite a confirmed 
![Screenshot_20190425-161111](https://user-images.githubusercontent.com/344917/56791184-b955a100-6806-11e9-8389-87c627460cc7.png)
"

**Comment by jjoseba** [comment]
This error, just like #815, is the way the app represents its contents. The "to export" and "to submit" figures represent the number of activity trackers registered in that device (saved in the local database), not the activity log files. The second part about transferring the files should be related with #813
