### ISSUE TITLE
com.github.fabioCollini:DaggerMock:0.6.2 in the app gradle file

### ISSUE THREAD

**Issue by hakimks** [DigitalCampus/oppia-mobile-android#824]
I was getting the following Error - ERROR: Unable to resolve dependency for ':app@adminDebugAndroidTest/compileClasspath': Could not resolve com.github.fabioCollini:DaggerMock:0.6.2.

**Comment by hakimks** [comment]
Solved this by replacing com.github.fabioCollini:DaggerMock:0.6.2 with androidTestImplementation 'com.github.fabioCollini.daggermock:daggermock:0.8.5' and also
repositories {
    maven { url "https://mint.splunk.com/gradle/" }
    maven { url "https://jitpack.io" }
}

in the app build.gradle file

**Comment by alexlittle** [comment]
Thanks @hakimks  - would you like to make a pull request for these updates so we can pull these updates into the core Oppia app too, thanks!
