### ISSUE TITLE
Points don't get restored when logging in on new install

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#853]
Nick noted that after he removes and reinstalls the app, then logs in again, the points aren't being restored, and the points start from zero again.
Potentially this is due to connecting to different servers or similar. But should check out that it is all functioning as we'd expect

**Comment by jbc25** [comment]
I tested this issue but I was fine. Probably Nick was testing with a new user and there was no time to sync the tracker before he reinstalled the app and no points were uploaded.
I added a new commit in issue-854 branch to launch the TrackerWorker when CourseIndexActivity resumes (the same behaviour than before the refactor)
