### ISSUE TITLE
AndroidX migration

### ISSUE THREAD

**Issue by jbc25** [DigitalCampus/oppia-mobile-android#858]

**Comment by alexlittle** [comment]
Just to check - I presume this isn't going to affect/impact the app being used on older versions of android?

**Comment by jbc25** [comment]
> Just to check - I presume this isn't going to affect/impact the app being used on older versions of android?

No, it should not affect to older versions. The big change with this was that almost all files were modified changing some dependencies package names from the support library to the new Jetpack library, but the behaviour and the compatibility is the same
