### ISSUE TITLE
Review Google Messaging GCM

### ISSUE THREAD

**Issue by jbc25** [DigitalCampus/oppia-mobile-android#860]
This framework is old and mostly deprecated

**Comment by alexlittle** [comment]
For now this call all be removed since it's not in use by any projects.,

**Comment by alexlittle** [comment]
I think there might be some other lines that can be removed related to this...

- in /build.gradle: classpath 'com.google.gms:google-services:3.2.0'
- in AndroidManifest.xml: com.google.android.gms.version
- the google-services.json file is no longer needed?

**Comment by jbc25** [comment]
You are right. I'm removing them
