### ISSUE TITLE
UI minor updates - after review

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#879]
- [x] scorecard page - using the green (hard coded), long course titles cut off
- [x] box around courses on homepage
- [x] course index - margin on left of activities
- [x] points page - default to week/month/year, & odd font sizes on  small screen size
- [x] course download - margin left/centre
- [x] course download - change green highlight for no courses (looks too much like the points)
- [x] course download - margin on "cards"
- [x] course download - draft display - currently in dark green
- [x] scorecard - top alignment when multiple course with different course title lengths
- [x] remove androidplot library
- [x] on activity graph page - points on page don't match those in bottom bar
- [x] redesign badges page
- [x] download media - download all and unselect - make as buttons
- [x] download media - use same 'card' layout
- [x] quiz feedback page... new design
- [x] comments in code to show which colours appear where
- [x] search results - use card design - smaller course icons, fix text sizes

**Comment by jbc25** [comment]
For the 2 pending items:

- Points don't match because the bottom bar points shows the total user points retrieved from the server and the total activities points are the points sum of every activity registered in the local database (these data is not being uploaded to the server currently). So for new registered users the points should match but for previous users who login in a new device these points won't match. It's not a bug, it is more related with the functional design

- How can we approach the design of the buttons in Download media screen?

**Comment by alexlittle** [comment]
Thanks @jbc25 
For item 1 I think it's more about how we can explain this in the comments here, so it;s clear what is going on. Maybe we should also add an FAQs to the documentation about this - maybe as an FAQs part under the Training & support section (https://oppiamobile.readthedocs.io/en/latest/index.html#training-support)
For item 2 the issue is mainly that when the 'select all' from the menu has been selected, it's very difficult to be clear about the 'Download selected' and 'unselect all' links... see:

![Screenshot_20191029-211111](https://user-images.githubusercontent.com/344917/67802930-be84f880-fa94-11e9-86fe-bc2211f82f51.png)
 It would be better if these "download selected" and "unselect all" links looked more like the download button in:

![Screenshot_20191029-210904](https://user-images.githubusercontent.com/344917/67803033-e6745c00-fa94-11e9-9f53-262a8bfc78fa.png)

**Comment by alexlittle** [comment]
BTW, I should be clear that this should be applied to the core Oppia, not just the LMH version (as the screenshots)

**Comment by jbc25** [comment]
Maybe we can place the "Unselect all" button in the overflow menu in the toolbar and leave just the Download selected" button with the button style?

**Comment by alexlittle** [comment]
Yes, I think that would be good

**Comment by jbc25** [comment]
I'm going to add a new issue for the explanation of the points in the docs so this checklist can be completed
