### ISSUE TITLE
Check gamification notifications working on new UI

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#885]

**Comment by jbc25** [comment]
This issue refers to the animation (the points circle fliping and moving up)?

**Comment by alexlittle** [comment]
Actually all the gamification, I don't get the bar coming up in the bottom with the notification there either. I checked my settings and it's set up to have the 'full' gamification (animation + sound etc)

**Comment by jbc25** [comment]
Yes, it was an issue with the full animation but it's already solved in previous sprint. I move it to review
