### ISSUE TITLE
Default course description = false in settings menu

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#890]
should be an option in the local.properties to set the default display of course description.
Might also need a way to override the existing setting - for example if an older version of the app was installed the course description defaulted to true. Setting the default now in the local.properties won't (I assume) override the existing setting

**Comment by jbc25** [comment]
I didn't understand the second part of the description. When adding this new setting, it should override the previous value or not?

**Comment by alexlittle** [comment]
Yes, I think we should have it override the previous value
