### ISSUE TITLE
Bluetooth - Automatically export activities when you open the sync menu

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#892]

**Comment by alexlittle** [comment]
Yes, it should be the same as the process as when the export activity button is pressed.
It should just be transparent to the user, but of course if it;s something that will take some time (a few seconds), then would be good to show progress to the user.
At this stage I don't think it needs to try to upload to the server.

I have bit of a concern about this issue, since it might then result in a lot of small activity log files that need to be downloaded/shared and then uploaded to the server. However, the sync/export process should only be available to device admin users, so hopefully not an issue

**Comment by jbc25** [comment]
A quick approach was already done. Maybe in the future we can discuss how to improve the process
