### ISSUE TITLE
Improve UI to make Bluetooth buttons more clear

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#893]

**Comment by jbc25** [comment]
We have a proposal for this? Change icons? Put text label below?

**Comment by alexlittle** [comment]
I think the icons are fine... it's just more about showing then more like buttons (more shadow or different colour).

At the moment it's not clear they are things that can be pressed on (rather than just info icons), see:

![Screenshot_20191029-220429](https://user-images.githubusercontent.com/344917/67806517-b2e90000-fa9b-11e9-8fdc-523b0306658b.png)

[again - should be applied to core oppia not just LMH app]

**Comment by jbc25** [comment]
How this looks like. It has a light theme color and some "elevation" effect.

![device-2019-10-30-142625](https://user-images.githubusercontent.com/5065766/67861989-95f71000-fb21-11e9-8f04-ac492dae8ee1.png)

**Comment by alexlittle** [comment]
Thanks - that looks good!
