### ISSUE TITLE
Allow exported activity logs to be directly uploaded to the server

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#895]
So the activity logs can be directly submitted from the app to the server - without the need to download the json file and then upload to the server manually.

I would suggest that once a log file has been successfully uploaded to the server it is automatically deleted from the device.

This shouldn't (I don;t think) require any changes to the server side - but correct me if I'm wrong!

**Comment by alexlittle** [comment]
If this functionality is already available, then we need to make clearer in the docs, esp on the https://oppiamobile.readthedocs.io/en/latest/implementers/offline/activity_log.html page - and post the updated info here on the github issue too

**Comment by alexlittle** [comment]
Actually there are a fair few things that are really unclear at the moment about this process and the specific activity log export page. Will update more once I've had a proper run through with Nick on the process.
but some initial things are:

- the 3 numbers on the top of the page are confusing - since one number shows number of specific trackers and other show the number of files.
- unclear if an activity log transferred from (eg) a health worker to a supervisor can actually then be automatically uploaded to the server. Esp since the files activity log json files seem to remain on the phone - if this data/file has been transferred successfully to the server, then it should be removed from this page.

**Comment by jjoseba** [comment]
For the issues in this last comment, I think they are covered in the docs - maybe it can be redacted clearer?
https://oppiamobile.readthedocs.io/en/latest/implementers/offline/activity_log.html

* The 3 numbers represent number of activities, none of them is the number of files
* If a device has activity logs, they are automatically uploaded to the server in the same task that pushes the DB trackers, it doesn't matter if they were activity logs generated from this device or transferred via bluetooth from another.
* The activity log files are removed from the device once they are transferred (to the server or to another device)

**Comment by alexlittle** [comment]
Thanks Joseba. I was testing this the other day and there are some things that aren't immediately obvious for users - I'll go through in more detail soon about the specific issues on this

**Comment by alexlittle** [comment]
Couple of things that I noticed with this (using v7.0.1 of the core app)...
it's showing me that there are trackers to export and to submit, but when I press the buttons to submit/export, the toast messages tell me everything has been submitted/exported, but the figures aren't updated, see:

![Screenshot_20191108-190547](https://user-images.githubusercontent.com/344917/68847774-e18beb00-06d7-11ea-93da-40b3bb270580.png)

and

![Screenshot_20191108-190556](https://user-images.githubusercontent.com/344917/68847791-e94b8f80-06d7-11ea-9836-dc1ffb172df3.png)

So not sure what is going on here...
