### ISSUE TITLE
Course layout issue when switching between landscape and portrait

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#901]
See: https://community.oppia-mobile.org/t/enlarged-course-tile-on-home-page/71 for image and better description

**Comment by jjoseba** [comment]
@jbc25, Seems like the RecyclerView is reusing a viewHolder that has a layout from the previous orientation (I guess that in landscape mode that device is big enough to use the tablet layout for the courses page).

**Comment by alexlittle** [comment]
@jjoseba  - if that's the case, a bit odd that it's just happening with one course though? Or am I misunderstanding?

**Comment by jbc25** [comment]
I reply on the forum to know the model of the device. It seems is related with the screen size, in addition of what Joseba said
