### ISSUE TITLE
Update activity log export for media/quiz

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#904]
In the activity log exports, it seems that media_played activities are not being marked as `type="media"` instead just being marked as `type=""`

Here's a snippet from an activity log file (identifying info replaced with '...'):

```
{
                    "data": "...",
                    "tracker_date": "2019-08-31 22:06:39",
                    "completed": 0,
                    "digest": "...",
                    "event": "media_played",
                    "points": 0,
                    "course": "...",
                    "type": ""
                },
```

**Comment by alexlittle** [comment]
Similarly with quiz attempts:

```
{
                    "type": "", 
                    "completed": 1, 
                    "course": "..", 
                    "points": 0, 
                    "tracker_date": "2019-02-13 14:50:06", 
                    "data": "...", 
                    "event": "quiz_attempt", 
                    "digest": "..."
                }, 
```

**Comment by jjoseba** [comment]
The "type" field in the tracker table is actually populated in the server, being the "search" type the only one that is explicitly provided. For the rest of them, the type is calculated based in the tracker digest (searching if it is a media file or a course activity, and updating the type based on it).
For the sake of clarity we can include the type for every exported element (both in activity logs and in API requests), but it is going to be updated in the server anyway...

**Comment by alexlittle** [comment]
Thanks! if it's being calculated by the server, then not much point it being added in the activity log tracker - as it'll just make the files bigger for no reason.
I think where I was confused was that I thought previously (in Ethiopia), the type was listed as media when there was a media_played, but it seems now that this gets entered as type=page.
I think it would be helpful to move back to this. It also links up I think to some of the other tracker log issues/checks that have come up this week

**Comment by jbc25** [comment]
This issue needed anything more?
