### ISSUE TITLE
Offline registration - create tests to check it's not case sensitive

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#913]
If a user registers offline, then logs out, but then re-registers in the app with a 'similar' username (only different case, i.e. 'Alex' vs 'alex'), these should be considered as the same user, it should not be creating a separate user accounts for 'Alex' and 'alex'.

Need to create some app tests to make sure this functions correctly

**Comment by jbc25** [comment]
discovered bug: when a user tries to register offline with a previously registered username the system log-in updating the user data. It should show a warning message to the user letting him know the username already exists.
