### ISSUE TITLE
Initial mockups for interface for user to see their quiz attempts (and responses) 

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#916]
At the moment the user can't look back at all their quiz attempts/responses - so need to add an interface for this in the app.

Firstly we need to make some mock ups for how this will display (and where it will be linked from), before finalising the tech dev.

The basic rationale for this is so that when supervisors visit users, they can review on the phone what the user has been doing.

**Comment by jjoseba** [comment]
Here is a first approach at it. The idea is that under the current course scorecard, when you press any of the quiz squares that appear below the piechart, it takes you to the detailed attempts for that quiz. There you would have a summary (total number of attempts, best and average) like in the server, and below that all the attempts for that particular quiz listed by date, showing the final score and using different colors to express if it was passed or not (we don't have much more info than this). If you press one of the attempts, you can see the detailed response, just like the feedback when you finish answering the quiz.

![quizzes](https://user-images.githubusercontent.com/6810415/70718383-61fe3580-1cf0-11ea-89cc-afd458ab4be9.png)


Another option would be to link somewhere (in the global scorecard maybe?) to an activity that displays all the attempts for every quiz in the app, but in my opinion this can look a bit chaotic.

**Comment by alexlittle** [comment]
Have added this to the community site (at: https://community.oppia-mobile.org/t/showing-quiz-attempts-responses-in-the-app/81) as think it will be easier to have the conversation there
