### ISSUE TITLE
Tracker meta-data not always being recorded

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#918]
In the tracker logs it seems that the meta-data that should be attached to every tracker data json is not always being added.... eg there are some tracker data json objects like this (correctly with full meta-data):

`{"network":"","simserial":"...","wifion":false,"netconnected":false,"battery":78,"lang":"en","timetaken":74,"mediafile":"xxxxx.mp4","media":"played","uuid":"xxxxx"}`

but others without the meta-data:

`{"lang":"en","timetaken":9,"mediafile":"xxxx.mp4","media":"played","uuid":"xxxx"}`

It seems to be happening certainly with media plays and quiz attempts.

Need to make sure this meta-data is added to every tracker (unclear why it's not, maybe if the device has no sim card or is disconnected from mobile network?) and also add some tests for this.

**Comment by jjoseba** [comment]
Does this happen for the same device/user? I mean, is something that happens sporadically for a user that sometimes submits correct data, or are there users that always submit this data and others that don't? 

There are a couple of causes that can make the metadata to not be saved:

* The telephony manager not being available: according to the documentation, this is not related with the device having a SIM card or network connectivity. Could be related with being an emulator or not having the permissions (but they are checked at startup, so for this to be the case, a user would have to open the app, put the app in the background, revert permissions in the app system settings and go back into the current app process). 

* After exploring the code for this functionality, I think this is the **most probable case**: the metadata that gets added in each tracker is based in the `OPPIA_METADATA` configuration in the server. This information is fetched when a user logs in or registers in the app. For devices that never performed any of this two actions, like preloaded accounts or offline registered users, this information is never fetched, so it does not get included.

Solutions:
* Make the default configuration without fetching from the server to include the metadata
* Make each metadata configuration a buidConfig value

**Comment by alexlittle** [comment]
Thanks, to me too it looks like the most likley case then is the fact the devices have never been connected to the server.
I think then it would be best to make the default build config values (which may then get updated if there is a server connection)
