### ISSUE TITLE
Refine course scorecard interface

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#921]
it's a bit tricky for people to understand what the figures etc on the course scorecard actually represent:
![Screenshot_20191108-120017](https://user-images.githubusercontent.com/344917/68478946-05a78200-0229-11ea-8f1b-e1ad526aee67.png)
 
For example the quiz attempts is not the number of times they've ever attempted any quiz, but the number of quizzes in the course that they've had at least one attempt at.

Similarly for the quiz scores (it's their max ever score for that quiz) and the boxes that represent each quiz, it's unclear how to know what quiz the score relates to.

Need to get the balance right here in terms of keeping the page clean vs the meaning of the data being clearer.

This issue may also be linked to showing the quiz attempts/responses: https://github.com/DigitalCampus/oppia-mobile-android/issues/916

As well as updating the interface here, need to update the docs so this information can be explained in more detail.

**Comment by jbc25** [comment]
Do we need to discuss the changes of this screen or there is already any proposal?

**Comment by alexlittle** [comment]
Combining this issue with #920 since they are related...
Currently we're using the term scorecard for both the 'global' one (that shows progress for all the courses on one screen) and for the course specific one - this is a little confusing for people to know what page they are actually talking about.

An initial idea is just to refer to the global one as the scorecard, and the course specific one to be renamed as 'course progress' .

Added to Community site: https://community.oppia-mobile.org/t/scorecard-terminology/77 - so awaiting feedback from there
