### ISSUE TITLE
LMH mockups for updated colours

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#938]
Create mockups only at this stage, with the following:

    Update the color of the progress circle to 
        CHA Emerald
        3272 C
        CMYK 94.0.48.0
        RGB 0.171.159
        #00AB9F 
    Update the color of the tick marks indicating an activity is complete to 
        CHA Orange
        487 C
        CMYK 0.53.54.0
        RGB 255.145.113
        #FF9171
    On the points graph, update the color of the small circles indicating dates and the points in the list (currently light blue) to CHA Emerald
    Points Leaderboard - I think this page could use some color, but I'm a bit stuck on what might look good. I'd love any suggestions you all might have.

**Comment by jjoseba** [comment]
I've made in-app changes to quickly visualize how each color would look like for this components:

Course piecharts (personally, I would stick with the original one): 

![piechart_colors](https://user-images.githubusercontent.com/6810415/69819495-665e2500-11ff-11ea-978f-a0de9fddd413.jpg)

Completion badge (any of them look nice):

![badge_colors](https://user-images.githubusercontent.com/6810415/69819523-7249e700-11ff-11ea-9089-173703560881.jpg)

**Comment by jbc25** [comment]
- Changed points graph circles color.
