### ISSUE TITLE
Improve protected by admin settings change flow

### ISSUE THREAD

**Issue by jbc25** [DigitalCampus/oppia-mobile-android#954]
PreferenceFragment in android has some limitations. You can listen for setting user click action but you cannot perform automatically a click action so this complicates to prompt admin password when user clicks an admin protected setting.

Now the flow is to change the setting and then prompt the admin password dialog. If the password is correct then perform the setting value change.

Figure out how to improve this

**Comment by alexlittle** [comment]
transferred to OPPIA-93
