### ISSUE TITLE
TransactionTooLargeException. Check if this is a general bug

### ISSUE THREAD

**Issue by jbc25** [DigitalCampus/oppia-mobile-android#961]
Error only appearing on a API 24 virtual device (in other virtual devices don't appear):
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1124548 bytes

If it appears on other devices, add a new Issue. This library can help:
https://github.com/guardian/toolargetool

**Comment by alexlittle** [comment]
I think it might be a more general bug... I had automated error for this with the following data:


OS | Android 9
-- | --
App Version | 7.0.0
Device | OnePlus ONEPLUS A6013
Country | Uknown
appVersionCode | 70
msFromStart | 2601971
user_id | XXXX
memAppAvailable | 1.98
appsRunning | None
memSysThreshold | 0
mobile_net_on | 1
gps_on | ON
sdk_version | 5.0.0
memAppMax | 256
build_uuid | None
architecture | None
wifi_on | 0
memSysLow | false
memSysAvailable | 236.46
memAppTotal | 11.68

see also: #924

**Comment by alexlittle** [comment]
transferred to OPPIA-90
