### ISSUE TITLE
Bluetooth transfer - clarify the user messages

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#976]
Clarify/add the messages that the user gets when the activity logs/courses/media get transferred between devices

@julie - please add any extra info/screenshots here as to which messages you think are missing, or that need to be updated

**Comment by jodette** [comment]
Hi Alex and team,

Sorry for the delay - we're hoping to clarify the messaging for a user when they receive a file transfer. The attached screenshot shows the message for a user when they have files to send, prompting them to Send Now. When the user sends the file, the receiving user sees the same message/image prompting them to send the files they just received. We want to clarify the messaging for the receiving user, to reduce the risk of someone accidentally sending the data they just received back to the sending user.

![Screenshot_20200110-220657](https://user-images.githubusercontent.com/55252848/72272014-ea287100-35f5-11ea-8b09-4024d66978a3.png)
